# Generated by Django 2.2.3 on 2019-08-20 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtor',
            old_name='hite_date',
            new_name='hire_date',
        ),
    ]
